# Generated by Django 2.0.7 on 2018-07-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='PizzaTT',
        ),
    ]
