# Generated by Django 2.0.7 on 2018-07-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20180723_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaTT',
            new_name='Pizza',
        ),
    ]
